### ISSUE TITLE
1 April - Shapes in Android UI

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/gla-mca4044-2019#4]
Write your entry in the format given below-
# Divyansh Bhardwaj, 1234567890

**Comment by vaishali-ag** [comment]
vaishali agrawal 60

**Comment by ashwani8090** [comment]
Ashwani Pratap singh -12 ,178420002

**Comment by anmolrajputit** [comment]
Anmol Singh 07

**Comment by Devendra-singh12** [comment]
Devendra kumar singh
17 (class roll no)
188429015 (university roll no.)

**Comment by satyamgupta20** [comment]
Satyam Gupta -46-178420006

**Comment by devAsad** [comment]
Mohd Asad 
Roll no. - 31

**Comment by VikasKumar1997** [comment]
name=vikas kumar
roll no. =62
me aaya tha class me

**Comment by RajatVarshney24** [comment]
Rajat Kumar varshney 
roll no -41

**Comment by shivji71** [comment]
Chhail bihari 
Roll NO. 15

**Comment by himanshuaskd** [comment]
Himanshu Mishra
Roll no 24

**Comment by kishorchat12** [comment]
Kishor Chaturvedi
Roll no. - 28

**Comment by UditMaheshwari** [comment]
Udit kumar
Roll no:-58

**Comment by Amitkumar371996** [comment]
Amit kumar 06

**Comment by amgauravok** [comment]
Gaurav Gupta
Roll no- 21

**Comment by Gunjika** [comment]
Gunjika
Roll no-22

**Comment by Gagankumarbansal** [comment]
Gagan Kumar Bansal- 20

**Comment by shivank-19** [comment]
Shivank chauhan
49(class roll no.)
188429043(university roll no.)

**Comment by utkarsh-agarwal** [comment]
utkarsh agarwal
roll no:-59

**Comment by Akash03Yadav** [comment]
Akash 03

**Comment by Neha2908** [comment]
Name: Neha Varshney
Roll No.:- 34

**Comment by Devangpachory** [comment]
devang pachory
roll no. 16

**Comment by navi123kumar** [comment]
naveen kumar
roll 33

**Comment by Nishiyadav09** [comment]
Nishi yadav
Roll no- 36

**Comment by rakshagoswami** [comment]
raksha goswami 42

**Comment by divyanshi0406** [comment]
Divyanshi sharma
Class rollno: 19

**Comment by themohit96** [comment]
Mohit Saxena
Roll No. 32

**Comment by ishneet25** [comment]
Ishneet Singh sarna
25

**Comment by vijaypal11** [comment]
Vijay pal Singh 61

**Comment by nikhilgupta29** [comment]
Nikhil Kumar Gupta, Roll No 35

**Comment by Viveksengar07** [comment]
vivek sengar
roll 64

**Comment by Shwetaagarwal1998** [comment]
shweta agarwal
53

**Comment by anubhav2510** [comment]
ANUBHAV BANSAL
ROLL NO. 08

**Comment by meghna-varshney** [comment]
Meghna Varshney
 roll no:- 30

**Comment by Rahulvarshney97** [comment]
rahul varshney
roll no - 40

**Comment by AshishChauhan31** [comment]
Ashish chauhan
Roll no . 10

**Comment by RenuTiwari1401** [comment]
Renu tiwari rollno 43

**Comment by Shuvamchoudhary-0822** [comment]
Shuvam Choudhary,52

**Comment by ShrutiAgrawal08** [comment]
shruti agrawal 50

**Comment by sunnykumaar** [comment]
Sunny Kumar
Roll no. 56

**Comment by Kamaltomar1** [comment]
KAMAL TOMAR
ROLL NO. 26
thank you.....................

**Comment by swatiAgarwal15** [comment]
Swati agarwal , 57

**Comment by alokpandey786** [comment]
Alok pandey
Roll...04

**Comment by Archi27** [comment]
Archi Agrawal
09

**Comment by dbc2201** [comment]
Dheeraj Gautam, 19

**Comment by dbc2201** [comment]
Sonal yadav, 55

**Comment by rahulgautam23** [comment]
rahul gautam
roll no.39

**Comment by pragatiprabha28** [comment]
pragati prabha
class rollno-37

**Comment by Rishavjohari** [comment]
Rishav johari 
Class roll no -44

**Comment by shubham28159** [comment]
Shubham verm
Class roll no -51

**Comment by soami1234** [comment]
Soami Prasad
54
